### PR TITLE
support page load commands for plugins

### PR DESCRIPTION
**Pull request by ataube**
Allow plugins to inject commands to be run immediately after the page load. 
@fgnass @sebashwa can u please review the code, thanks :-)

### CODE REVIEW

**Comment by fgnass** [comment]
Just a thought: If retractor returned `undefined` when queried while its not yet loaded, our new `.find()` implementation (which does an implicit wait) would just retry invoking it.

**Comment by ataube** [comment]
No sure if I get you, can the `find()` lookup window properties like `window.__retractor`?

**Comment by ataube** [comment]
But you are right, regarding retractor we need a mechanism to retry until we are sure the plugin is loaded correctly

**Comment by sebashwa** [comment]
Looks good to me regarding the code implementation! What do you need it for? Does retractor have to do something on page load?

**Comment by ataube** [comment]
@sebashwa exactly, retractor gets initialized with the react dev tools hook and we have to wait for this to happen.

**Comment by ataube** [comment]
I close this pull request, the feature is not needed anymore

**Pull request closed without merging**
